config/routes.rb
Rails.application.routes.draw do
  
  resources :skills
  resources :roles
  resources :qualifications
  # get 'topics/index'
  # get 'topics/show'

  # the above only creates these routes (autogenerated via rails g controller index show)
  # topics_index GET    /topics/index(.:format)                                                                  topics#index
  # topics_show GET    /topics/show(.:format)                                                                   topics#show

  # so a better way to do this... since we have a topic model
  resources :topics, only: [:index, :show]
  # this generates the following nicer routes, and gives as the :id parameter
  # topics GET    /topics(.:format)                                                                        topics#index
  # topic GET    /topics/:id(.:format)                                                                    topics#show

  # :comments generated by rails g resoure Comment ....
  # once implemented action cable, this not needed, as action cable provides access to web sockets, so not standard http routing
  # resources :comments
  
  
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  # resources :portfolio_items, except: [:show] do
  #   put :sort, on: collection
  # end


  # resources :portfolio_items, except: [:show] do
  # decided not to override the show path as has path-generatin side effects I've not figured out around yet
    resources :portfolio_items do
      collection do
			put 'sort'
		end
    # resources :portfolio_items, except: [:show] do
    #   put :sort, on: collection
    # end

		# member do
		# 	put 'some_method'
		# end
	end

  get 'rails_items', to: 'portfolio_items#ruby_on_rails_portfolio_items'
  

  get 'javascript_items', to: 'portfolio_items#javascript_portfolio_items'
  # override default plural to make singular
  # decided not to override the show path as has path-generatin side effects I've not figured out around yet
  # get 'portfolio_item/:id', to: 'portfolio_items#show', as: 'portfolio_item_show'
  # get 'portfolio_items/:id', to: 'portfolio_items#show', as: 'portfolio_item_show'

  # get 'pages/home'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'
  get 'course_completion', to: 'pages#course_completion'
  
  resources :blogs do
    member do
      get :toggle_status
    end
  end

  # perhaps change this to comments_cable ??
  # this uses web sockets, so standard route for comments not needed... see at top
  mount ActionCable.server => '/cable'

  root 'pages#home'
  # root to: 'pages#home'
  # get 'home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/qualification.rb
class Qualification < ApplicationRecord
end

app/controllers/qualifications_controller.rb
class QualificationsController < ApplicationController
  before_action :set_qualification, only: [:show, :edit, :update, :destroy]
  access site_admin: :all

  # GET /qualifications
  def index
    @qualifications = Qualification.all
  end

  # GET /qualifications/1
  def show
  end

  # GET /qualifications/new
  def new
    @qualification = Qualification.new
  end

  # GET /qualifications/1/edit
  def edit
  end

  # POST /qualifications
  def create
    @qualification = Qualification.new(qualification_params)

    if @qualification.save
      redirect_to @qualification, notice: 'Qualification was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /qualifications/1
  def update
    if @qualification.update(qualification_params)
      redirect_to @qualification, notice: 'Qualification was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /qualifications/1
  def destroy
    @qualification.destroy
    redirect_to qualifications_url, notice: 'Qualification was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qualification
      @qualification = Qualification.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def qualification_params
      params.require(:qualification).permit(:title, :institution, :year_obtained, :description)
    end
end

app/helpers/qualifications_helper.rb
module QualificationsHelper
end

app/views/qualifications/_form.html.erb
<%= form_with(model: qualification, local: true) do |form| %>
<% if qualification.errors.any? %>
<div id="error_explanation">
  <h2>
    <%= pluralize(qualification.errors.count, "error") %> prohibited this qualification from being saved:</h2>

  <ul>
    <% qualification.errors.full_messages.each do |message| %>
    <li>
      <%= message %>
    </li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= form.label :title %>
  <%= form.text_field :title %>
</div>

<div class="field">
  <%= form.label :institution %>
  <%= form.text_field :institution %>
</div>

<div class="field">
  <%= form.label :year_obtained %>
  <%= form.number_field :year_obtained %>
</div>

<div class="field">
  <%= form.label :description %>
  <%= form.text_area :description %>
</div>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/qualifications/edit.html.erb
<h1>Editing Qualification</h1>

<%= render 'form', qualification: @qualification %>

<%= link_to 'Show', @qualification %> |
<%= link_to 'Back', qualifications_path %>

app/views/qualifications/index.html.erb
<p id="notice">
  <%= notice %>
</p>

<h1>Qualifications</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Institution</th>
      <th>Year obtained</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @qualifications.each do |qualification| %>
    <tr>
      <td>
        <%= qualification.title %>
      </td>
      <td>
        <%= qualification.institution %>
      </td>
      <td>
        <%= qualification.year_obtained %>
      </td>
      <td>
        <%= qualification.description %>
      </td>
      <td>
        <%= link_to 'Show', qualification %>
      </td>
      <td>
        <%= link_to 'Edit', edit_qualification_path(qualification) %>
      </td>
      <td>
        <%= link_to 'Destroy', qualification, method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Qualification', new_qualification_path %>

app/views/qualifications/new.html.erb
<h1>New Qualification</h1>

<%= render 'form', qualification: @qualification %>

<%= link_to 'Back', qualifications_path %>

app/views/qualifications/show.html.erb
<p id="notice">
  <%= notice %>
</p>

<p>
  <strong>Title:</strong>
  <%= @qualification.title %>
</p>

<p>
  <strong>Institution:</strong>
  <%= @qualification.institution %>
</p>

<p>
  <strong>Year obtained:</strong>
  <%= @qualification.year_obtained %>
</p>

<p>
  <strong>Description:</strong>
  <%= @qualification.description %>
</p>

<%= link_to 'Edit', edit_qualification_path(@qualification) %> |
<%= link_to 'Back', qualifications_path %>