config/routes.rb
Rails.application.routes.draw do
  
  resources :skills
  resources :roles
  resources :qualifications
  # get 'topics/index'
  # get 'topics/show'

  # the above only creates these routes (autogenerated via rails g controller index show)
  # topics_index GET    /topics/index(.:format)                                                                  topics#index
  # topics_show GET    /topics/show(.:format)                                                                   topics#show

  # so a better way to do this... since we have a topic model
  resources :topics, only: [:index, :show]
  # this generates the following nicer routes, and gives as the :id parameter
  # topics GET    /topics(.:format)                                                                        topics#index
  # topic GET    /topics/:id(.:format)                                                                    topics#show

  # :comments generated by rails g resoure Comment ....
  # once implemented action cable, this not needed, as action cable provides access to web sockets, so not standard http routing
  # resources :comments
  
  
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  # resources :portfolio_items, except: [:show] do
  #   put :sort, on: collection
  # end


  # resources :portfolio_items, except: [:show] do
  # decided not to override the show path as has path-generatin side effects I've not figured out around yet
    resources :portfolio_items do
      collection do
			put 'sort'
		end
    # resources :portfolio_items, except: [:show] do
    #   put :sort, on: collection
    # end

		# member do
		# 	put 'some_method'
		# end
	end

  get 'rails_items', to: 'portfolio_items#ruby_on_rails_portfolio_items'
  

  get 'javascript_items', to: 'portfolio_items#javascript_portfolio_items'
  # override default plural to make singular
  # decided not to override the show path as has path-generatin side effects I've not figured out around yet
  # get 'portfolio_item/:id', to: 'portfolio_items#show', as: 'portfolio_item_show'
  # get 'portfolio_items/:id', to: 'portfolio_items#show', as: 'portfolio_item_show'

  # get 'pages/home'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'
  get 'course_completion', to: 'pages#course_completion'
  
  resources :blogs do
    member do
      get :toggle_status
    end
  end

  # perhaps change this to comments_cable ??
  # this uses web sockets, so standard route for comments not needed... see at top
  mount ActionCable.server => '/cable'

  root 'pages#home'
  # root to: 'pages#home'
  # get 'home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_alerts.html.erb
<% if flash[:alert] %>

<%= js add_gritter(flash[:alert], :title => "Peter Torr Smith - Portfolio") %>
<% elsif flash[:notice] %>
<%= js add_gritter(flash[:notice], :title => "Hey!") %>
<% elsif flash[:error] %>
<%= js add_gritter(flash[:error], :title => "Peter Torr Smith - Portfolio") %>
<% end %>

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto">
    <div class="inner">
        <!-- <p>Cover template for <a href="https://getbootstrap.com/">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p> -->
        <p class="app-footer">
            <%= copyright_generator %> | Version 2.7.13
        </p>
    </div>
</footer>

app/views/shared/_application_nav.html.erb
<header class="masthead mb-auto">
    <div class="inner">
        <h3 class="masthead-brand"><%=link_to 'Peter Torr Smith', root_path %></h3>
        <nav class="nav nav-masthead justify-content-center app-nav">

            <%= nav_helper 'nav-link', 'span' %>

            <!-- nav moved to helper -->
            <!--
            <%#= link_to "Home", root_path, class: "nav-link active" %>
            <%#= link_to "About", about_me_path, class: "nav-link" %>
            <%#= link_to "Contact", contact_path, class: "nav-link" %>
            <%#= link_to "Blogs", blogs_path, class: "nav-link" %>
            <%#= link_to "Portfolio", portfolio_items_path, class: "nav-link" %>
            -->

            <%= login_helper "nav-link" %>

        </nav>
    </div>
</header>

app/views/shared/_blog_footer.html.erb
<!-- start blog footer -->
<footer class="blog-footer">
    <p>
        <%=copyright_generator %>
        <p>
            <a href="#">Back to top</a>
        </p>
</footer>
<!-- end blog footer -->

app/views/shared/_blog_masthead.html.erb
<!-- start blog header -->
<div class="blog-header">
    <div class="container">
        <h1 class="blog-title">
            <%= link_to 'Blogs', blogs_path %>
        </h1>
        <p class="lead blog-description">What's going down :-)</p>
        <% if logged_in?(:site_admin)%>
        <span class="masthead-link">
            <%= link_to 'Create a new Blog', new_blog_path, class: 'btn-sm btn-secondary'%>
        </span> |
        <span class="masthead-link">
            <%= link_to "topics list", topics_path %>
        </span>
        <% end %>
    </div>
</div>
<!-- end blog header -->

app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light blog-nav">
    <div class="container">
        <%= link_to "Peter Torr Smith", root_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarSupportedContent"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarContent">
            <ol class="navbar-nav mr-auto">
                <%= nav_helper 'nav-link', 'li' %>
                <%= login_helper 'nav-link' %>
            </ol>
        </div>

    </div>

</nav>


<%#= nav_helper 'nav-link', 'span' %>

<%#= login_helper 'nav-link' %>












<!-- Start blog nav -->
<!-- <div class="blog-masthead">
    <div class="container">
        <nav class="nav blog-nav"> -->

<!-- from bootstrap example -->
<!-- 
            <a class="nav-link active" href="#">New features</a>
            <a class="nav-link" href="#">Press</a>
            <a class="nav-link" href="#">New hires</a>
            <a class="nav-link" href="#">About</a> 
            -->

<%#= nav_helper 'nav-link', 'span' %>

<!-- nav moved to helper -->
<!-- 
            <%#= link_to "Home", root_path, class: "nav-link" %>
            <%#= link_to "About", about_me_path, class: "nav-link" %>
            <%#= link_to "Contact", contact_path, class: "nav-link" %>
            <%#= link_to "Blogs", blogs_path, class: "nav-link active" %>
            <%#= link_to "Portfolio", portfolio_items_path, class: "nav-link" %>
            -->

<%#= login_helper 'nav-link' %>
<!-- </nav>
    </div>
</div> -->
<!-- end blog nav -->

app/views/shared/_blog_sidebar.html.erb
<!-- start sidebar -->
<div class="col-sm-3 offset-sm-1 blog-sidebar">
    <!-- <div class="sidebar-module">
        <h4>About</h4>
        <p>coming soon</p>
    </div> -->

    <div class="sidebar-module sidebar-module-inset">
        <h4>Blog topics</h4>
        <% @sidebar_topics.each do |topic| %>
        <div class="sidebar-topic-link">
            <%= link_to topic.title, topic_path(topic) %>
        </div>
        <% end %>
    </div>
    <div class="sidebar-module">
        <h4>Elsewhere</h4>
        <ol class="list-unstyled social-links">
            <li><a href="//github.com/ptorrsmith" target="_blank">
                    <%= fa_stacked_icon "github" %>
                </a></li>
            <%#= content_tag(:li, fa_stacked_icon("check li", text: "Check baby, check!")) %>
            <li><a href="//facebook.com/ptorrsmith" target="_blank">
                    <%= fa_stacked_icon "facebook" %>
                </a></li>
            <li><a href="//twitter.com/ptorrsmith" target="_blank">
                    <%= fa_stacked_icon "twitter" %>
                </a></li>
            <li><a href="//www.linkedin.com/in/ptorrsmith/" target="_blank">
                    <%= fa_stacked_icon "linkedin" %>
                </a></li>
        </ol>
    </div>
</div><!-- /.blog-sidebar -->
<!-- end sidebar -->

app/views/shared/_nav.html.erb
<!-- no longer used ? -->
<p>You shouldn't see this</p>
<p>find me in shared/_nav.html.rb</p>
<!-- 
<div class="<%#= location %>">
    <div> <%#= link_to "Home", root_path %> </div>
    <div> <%#= link_to "About", about_me_path %> </div>
    <div> <%#= link_to "Contact", contact_path %> </div>
    <div> <%#= link_to "Blogs", blogs_path %> </div>
    <div> <%#= link_to "Portfolio", portfolio_items_path %> </div>
</div> 
-->

app/views/shared/_portfolio_footer.html.erb
<!-- start of footer -->
<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Back to top</a>
        </p>
        <p>
            <%= copyright_generator %>
        </p>
        <p>
            <%= source_helper("portfolio_items") %>
        </p>
    </div>
</footer>
<!-- end of footer -->

app/views/shared/_portfolio_masthead.html.erb
<!-- start of masthead -->

<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">
            <%= link_to 'Portfolio and Work', portfolio_items_path %>
        </h1>
        <p class="lead text-muted">Some highlights</p>
        <p>
            <%= link_to "Get in touch", contact_path, class: "btn btn-primary my-2" %>
            <%= link_to "Recent blogs", blogs_path, class: "btn btn-secondary my-2" %>
            <!-- <a href="#" class="btn btn-primary my-2">Main call to action</a>
            <a href="#" class="btn btn-secondary my-2">Secondary action</a> -->
        </p>

    </div>
</section>

<!-- end of masthead -->

app/views/shared/_portfolio_nav.html.erb
<!-- start nav -->

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white">About my work</h4>
                    <p class="text-muted">This showcases a few projects, programmes, products and ventures I've been
                        fortunate to have been a part of making real :-)</p>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4 class="text-white">Explore</h4>
                    <ul class="list-unstyled">

                        <%= nav_helper 'text-white', 'li' %>


                        <!-- <li><a href="#" class="text-white">Follow on Twitter</a></li>
                            <li><a href="#" class="text-white">Like on Facebook</a></li>
                            <li><a href="#" class="text-white">Email me</a></li> -->

                        <!-- old nav, before nav-helper -->
                        <!-- 
                            <li>
                            <%#= link_to "Home", root_path, class: "text-white" %>
                        </li>
                        <li>
                            <%#= link_to "About", about_me_path, class: "text-white" %>
                        </li>
                        <li>
                            <%#= link_to "Contact", contact_path, class: "text-white" %>
                        </li>
                        <li>
                            <%#= link_to "Blogs", blogs_path, class: "text-white active" %>
                        </li>
                        <li>
                            <%#= link_to "Portfolio", portfolio_items_path, class: "text-white" %>
                        </li>
                    -->
                        <li>
                            <%= login_helper 'text-white' %>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>


    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container d-flex justify-content-between">
            <a href=<%=root_path %> class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                    stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2" focusable="false"
                    aria-hidden="true">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
                    <circle cx="12" cy="13" r="4"></circle>
                </svg>
                <strong>Peter Torr Smith</strong>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

<!-- end nav top -->

app/views/shared/_roles_quals_cv.html.erb
<p class='text-center'>
    <% if @roles.count > 0 %>
    <button class="btn btn-primary collapsed shadow mb-2" type="button" data-toggle="collapse" data-target="#jobHistory"
        aria-expanded="false" aria-controls="jobHistory">Work History and roles</button>
    <% end %>
    <% if @qualificaitons.count > 0 %>
    <button class="btn btn-success collapsed shadow mb-2" type="button" data-toggle="collapse" data-target="#qualifications"
        aria-expanded="false" aria-controls="qualifications">Qualifications</button>
    <% end %>
    <%= link_to (fa_icon "external-link-square", text: "Download Profile/CV (Product/Team/Delivery focus)", right: true), '/docs/Peter Torr Smith - Product and Delivery - Profile April 2025.pdf', target: '_blank', class: 'btn btn-info text-white shadow mb-2' %>
    <%= link_to (fa_icon "external-link-square", text: "Download Profile/CV (Engineering focus)", right: true), '/docs/Peter Torr Smith - Engineering - Profile April 2025.pdf', target: '_blank', class: 'btn btn-info text-white shadow mb-2' %>

</p>

<div id="accordion">
    <div class="collapse" id="jobHistory" data-parent="#accordion">
        <% @roles.each do |role| %>
        <div class="card card-block role-card">
            <h5>
                <%= role.organisation %>
            </h5>
            <h6>
                <%= role.roles %>
            </h6>
            <p>From:
                <%= role.from.year %>. To:
                <%= role.current? ? 'current': "#{role.to.year}" %>.
                <%#=role.to? role.to.year : 'current' %>
            </p>
            <p>
                <%=role.description %>
            </p>
        </div>
        <% end %>
        <br />
    </div>
    <div class="collapse" id="qualifications" data-parent="#accordion">
        <% @qualificaitons.each do |qual| %>
        <div class="card card-block qualification-card">
            <h5>
                <%= qual.title %>
                <%= "(#{qual.year_obtained})"%>
            </h5>
            <h6>
                <%= qual.institution %>
            </h6>
            <p>
                <%=qual.description %>
            </p>
        </div>
        <% end %>
        <br />
    </div>
</div>