config/routes.rb
Rails.application.routes.draw do
  
  resources :skills
  resources :roles
  resources :qualifications
  # get 'topics/index'
  # get 'topics/show'

  # the above only creates these routes (autogenerated via rails g controller index show)
  # topics_index GET    /topics/index(.:format)                                                                  topics#index
  # topics_show GET    /topics/show(.:format)                                                                   topics#show

  # so a better way to do this... since we have a topic model
  resources :topics, only: [:index, :show]
  # this generates the following nicer routes, and gives as the :id parameter
  # topics GET    /topics(.:format)                                                                        topics#index
  # topic GET    /topics/:id(.:format)                                                                    topics#show

  # :comments generated by rails g resoure Comment ....
  # once implemented action cable, this not needed, as action cable provides access to web sockets, so not standard http routing
  # resources :comments
  
  
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  # resources :portfolio_items, except: [:show] do
  #   put :sort, on: collection
  # end


  # resources :portfolio_items, except: [:show] do
  # decided not to override the show path as has path-generatin side effects I've not figured out around yet
    resources :portfolio_items do
      collection do
			put 'sort'
		end
    # resources :portfolio_items, except: [:show] do
    #   put :sort, on: collection
    # end

		# member do
		# 	put 'some_method'
		# end
	end

  get 'rails_items', to: 'portfolio_items#ruby_on_rails_portfolio_items'
  

  get 'javascript_items', to: 'portfolio_items#javascript_portfolio_items'
  # override default plural to make singular
  # decided not to override the show path as has path-generatin side effects I've not figured out around yet
  # get 'portfolio_item/:id', to: 'portfolio_items#show', as: 'portfolio_item_show'
  # get 'portfolio_items/:id', to: 'portfolio_items#show', as: 'portfolio_item_show'

  # get 'pages/home'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'
  get 'course_completion', to: 'pages#course_completion'
  
  resources :blogs do
    member do
      get :toggle_status
    end
  end

  # perhaps change this to comments_cable ??
  # this uses web sockets, so standard route for comments not needed... see at top
  mount ActionCable.server => '/cable'

  root 'pages#home'
  # root to: 'pages#home'
  # get 'home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/role.rb
class Role < ApplicationRecord
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]
  # access all: [:index, :show, :new, :edit, :create, :update, :destroy], user: :all
  access site_admin: :all
  # GET /roles
  def index
    @roles = Role.all
  end

  # GET /roles/1
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  def create
    @role = Role.new(role_params)

    if @role.save
      redirect_to @role, notice: 'Role was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /roles/1
  def update
    if @role.update(role_params)
      redirect_to @role, notice: 'Role was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /roles/1
  def destroy
    @role.destroy
    redirect_to roles_url, notice: 'Role was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def role_params
      params.require(:role).permit(:organisation, :location, :from, :to, :current, :roles, :description, :highlights)
    end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<%= form_with(model: role, local: true) do |form| %>
<% if role.errors.any? %>
<div id="error_explanation">
  <h2>
    <%= pluralize(role.errors.count, "error") %> prohibited this role from being saved:</h2>

  <ul>
    <% role.errors.full_messages.each do |message| %>
    <li>
      <%= message %>
    </li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= form.label :organisation %>
  <%= form.text_field :organisation %>
</div>

<div class="field">
  <%= form.label :location %>
  <%= form.text_field :location %>
</div>

<div class="field">
  <%= form.label :from %>
  <%= form.date_select :from, start_year: 1980 %>
</div>

<div class="field">
  <%= form.label :to %>
  <%= form.date_select :to, start_year: 1980 %>
</div>

<div class="field">
  <%= form.label :current %>
  <%= form.check_box :current %>
</div>

<div class="field">
  <%= form.label :roles %>
  <%= form.text_area :roles %>
</div>

<div class="field">
  <%= form.label :description %>
  <%= form.text_area :description %>
</div>

<div class="field">
  <%= form.label :highlights %>
  <%= form.text_area :highlights %>
</div>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing Role</h1>

<%= render 'form', role: @role %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<p id="notice">
  <%= notice %>
</p>

<h1>Roles</h1>

<table>
  <thead>
    <tr>
      <th>Organisation</th>
      <th>Location</th>
      <th>From</th>
      <th>To</th>
      <th>Roles</th>
      <th>Description</th>
      <th>Highlights</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
    <tr>
      <td>
        <%= role.organisation %>
      </td>
      <td>
        <%= role.location %>
      </td>
      <td>
        <%= role.from %>
      </td>
      <% if role.current %>
      <td>current</td>
      <% else %>
      <td>
        <%= role.to %>
      </td>
      <% end %>
      <td>
        <%= role.roles %>
      </td>
      <td>
        <%= role.description %>
      </td>
      <td>
        <%= role.highlights %>
      </td>
      <td>
        <%= link_to 'Show', role %>
      </td>
      <td>
        <%= link_to 'Edit', edit_role_path(role) %>
      </td>
      <td>
        <%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Role', new_role_path %>

app/views/roles/new.html.erb
<h1>New Role</h1>

<%= render 'form', role: @role %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p id="notice">
  <%= notice %>
</p>

<p>
  <strong>Organisation:</strong>
  <%= @role.organisation %>
</p>

<p>
  <strong>Location:</strong>
  <%= @role.location %>
</p>

<p>
  <strong>From:</strong>
  <%= @role.from %>
</p>

<p>
  <strong>To:</strong>
  <% if @role.current %>
  current
  <% else %>
  <%= @role.to %>
  <% end %>
</p>

<p>
  <strong>Roles:</strong>
  <%= @role.roles %>
</p>

<p>
  <strong>Description:</strong>
  <%= @role.description %>
</p>

<p>
  <strong>Highlights:</strong>
  <%= @role.highlights %>
</p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>