config/routes.rb
Rails.application.routes.draw do
  
  resources :skills
  resources :roles
  resources :qualifications
  # get 'topics/index'
  # get 'topics/show'

  # the above only creates these routes (autogenerated via rails g controller index show)
  # topics_index GET    /topics/index(.:format)                                                                  topics#index
  # topics_show GET    /topics/show(.:format)                                                                   topics#show

  # so a better way to do this... since we have a topic model
  resources :topics, only: [:index, :show]
  # this generates the following nicer routes, and gives as the :id parameter
  # topics GET    /topics(.:format)                                                                        topics#index
  # topic GET    /topics/:id(.:format)                                                                    topics#show

  # :comments generated by rails g resoure Comment ....
  # once implemented action cable, this not needed, as action cable provides access to web sockets, so not standard http routing
  # resources :comments
  
  
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  # resources :portfolio_items, except: [:show] do
  #   put :sort, on: collection
  # end


  # resources :portfolio_items, except: [:show] do
  # decided not to override the show path as has path-generatin side effects I've not figured out around yet
    resources :portfolio_items do
      collection do
			put 'sort'
		end
    # resources :portfolio_items, except: [:show] do
    #   put :sort, on: collection
    # end

		# member do
		# 	put 'some_method'
		# end
	end

  get 'rails_items', to: 'portfolio_items#ruby_on_rails_portfolio_items'
  

  get 'javascript_items', to: 'portfolio_items#javascript_portfolio_items'
  # override default plural to make singular
  # decided not to override the show path as has path-generatin side effects I've not figured out around yet
  # get 'portfolio_item/:id', to: 'portfolio_items#show', as: 'portfolio_item_show'
  # get 'portfolio_items/:id', to: 'portfolio_items#show', as: 'portfolio_item_show'

  # get 'pages/home'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'
  get 'course_completion', to: 'pages#course_completion'
  
  resources :blogs do
    member do
      get :toggle_status
    end
  end

  # perhaps change this to comments_cable ??
  # this uses web sockets, so standard route for comments not needed... see at top
  mount ActionCable.server => '/cable'

  root 'pages#home'
  # root to: 'pages#home'
  # get 'home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/portfolio_item.rb
class PortfolioItem < ApplicationRecord
    # require 'carrierwave'
    has_many :technologies # , inverse_of: :portfolio_item  # need to explore what this brings... see https://www.viget.com/articles/exploring-the-inverse-of-option-on-rails-model-associations/ and https://guides.rubyonrails.org/association_basics.html
    accepts_nested_attributes_for   :technologies, 
                                    allow_destroy: true,
                                    reject_if: lambda { |attrs| attrs['name'].blank? }
    
    # include PlaceholderImage  # concern
    # validates_presence_of :title, :body, :main_image, :thumb_image
    validates_presence_of :title, :body # due to move to carrierwave uploader (and remove image management out of the model, into a helper)
    
    # this says how to manage (interpret) and present the thumb and main image... as a PortfolioItemUploder object.
    # our uploader is in the lib directory, so we need to mount it as the control for our thumb and main image fields
    mount_uploader :thumb_image, PortfolioItemUploader
    mount_uploader :main_image, PortfolioItemUploader
    
    ################## SCOPES - 2 styles / approaches / options  ############################
    # define scope option 1
    def self.javascript
        where(subtitle: 'Javascript')  # one way
    end

    # define scope option 2 (using the lambda construct)
    scope :ruby_on_rails_portfolio_items, -> { where(subtitle: 'Ruby on Rails')}
    
    ################## END - SCOPES - 2 styles / approaches / options  ############################


    def self.by_position
        # this is called a  "scope", refining the default data set (order, where, etc)
        order('position asc')
    end




    # after_initialize :set_defaults

    # def set_defaults
    #     # not using concerns
    #     # self.main_image ||= 'http://placehold.it/600x400'
    #     # self.thumb_image ||= 'http://placehold.it/350x200'

    #     # using concerns, initially (later moved to portfolio_items_helper.rb)

    #     # set these to portfolio defaults
    #     self.main_image ||= PlaceholderImage.image_generator(height: '600', width: '450')
    #     self.thumb_image ||= PlaceholderImage.image_generator(height: 356, width: 280)
    # end

    # Finally: Move image management out of the model, into a helper that takes into account carrierwave 

end

app/controllers/portfolio_items_controller.rb
class PortfolioItemsController < ApplicationController

    
    # before_action :set_portfolio_item, only: [:show, :edit, :update, :destroy]
    before_action :set_portfolio_item, only: [:show, :edit, :update, :destroy]
    
    # layout 'portfolio_items' # why different ? not needed anymore in rails 5.1/5.2 ?

    # don't seem to need all: block yet as anon is a GuestUser so is covered by user: Not ideal
    access user: {except: [:destroy, :new, :create, :update, :edit, :sort ]}, site_admin: :all
    
    #  Why can anon / user see :javascript_items if left off all?
    # access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, ]}, site_admin: :all
    # access all: [:show, :index, :javascript_portfolio_items], user: {except: [:destroy, :new, :create, :update, :edit, ]}, site_admin: :all
    # examples:
    # access all: [:show, :index], user: {except: [:destroy]}, company_admin: :all
    # # one other option that might seem a bit weird is to put a group of roles in an array:
    # access [:all, :user] => [:show, :index]
  

    # for ajax sort call
    def sort
        # params[:order].each | item | do

        params[:order].each do |key, value|
            
            # binding.pry
            
            # puts "************** params **************"
            # puts params
            # puts "************************************"
            # puts "^^^^^^^^^^^^^^^^^^^^ key, value ^^^^^^^^^^^^^^^^^^^^"
            # puts key
            # puts value[:id]
            # puts value[:position]
            # puts "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"

            # update the appropriate portfolio_item with it's new position value from the ajax call
            PortfolioItem.find(value[:id]).update(position: value[:position])
        end

        render body: nil
        # old pre 5.1 syntax
        # render nothing: true

    end

    def index
        @page_title = 'Peter Torr Smith - Portfolio'
        # @portfolio_items = PortfolioItem.all
        # # this is called a  "scope", refining the default data set
        # @portfolio_items = PortfolioItem.order('position ASC')
        @portfolio_items = PortfolioItem.by_position
        # binding.pry
    end
    
    def ruby_on_rails_portfolio_items
        @rails_portfolio_items = PortfolioItem.ruby_on_rails_portfolio_items       
        @portfolio_items = @rails_portfolio_items
        render 'portfolio_items/index'
    end
    
    def javascript_portfolio_items
        @javascript_portfolio_items = PortfolioItem.javascript
        @portfolio_items = @javascript_portfolio_items
        
    #  binding.pry
        
        render 'portfolio_items/index'
        # render 'portfolio_items/javascript_portfolio_items'
    end

    def new
        @portfolio_item = PortfolioItem.new
        # 3.times { @portfolio_item.technologies.build } # removed now as doing technolgy add/remove via javascript and cocoon
    end

    def create
        @portfolio_item = PortfolioItem.new(portfolio_item_params)
        # @portfolio_item = PortfolioItem.new(params.require(:portfolio_item).permit(:title, :subtitle, :body, :main_image, :thumb_image, technologies_attributes: [:name]))
        respond_to do |format|
            if @portfolio_item.save
                # format.html { redirect_to portfolio_item_show_path(@portfolio_item), notice: 'Portfolio Item was made gud mate!' }
                format.html { redirect_to @portfolio_item, notice: 'Portfolio Item was made gud mate!' }
                #   format.json { render :show, status: :created, location: @portfolio_item }
            else
              format.html { render :new } # perhaps hould be redirect to new?
            #   format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
            end
          end
    end

    def show
        @page_title = 'Peter Torr Smith - ' + @portfolio_item.title
# binding.pry
    end

    def edit
        # 3.times { @portfolio_item.technologies.build }

    
    end

    def destroy
        @portfolio_item.destroy
        respond_to do |format|
        format.html { redirect_to portfolio_items_url, notice: "Portfolio Item #{@portfolio_item.id} was successfully destroyed." }
        format.json { head :no_content }
    end
    
    end

    def update
        respond_to do |format|
            if @portfolio_item.update(portfolio_item_params)
                # format.html { redirect_to portfolio_items_path, notice: 'Portfolio Item was updated gud buddy!' }
                format.html { redirect_to @portfolio_item, notice: 'Portfolio Item was updated gud buddy!' }
            #   format.json { render :show, status: :created, location: @portfolio_item }
            else
              format.html { render :new }
            #   format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
            end
          end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio_item
      @portfolio_item = PortfolioItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def portfolio_item_params
        # this is called Strong Params
        # params.require(:portfolio_item).permit(:title, :subtitle, :body, technologies_attributes: [:name], :main_image, :thumb_image)
        # NOTE: nested attributes expected at end of params list, not middle (as above which fails)
        params.require(:portfolio_item).permit( :title, 
                                                :subtitle, 
                                                :body, 
                                                :main_image, 
                                                :thumb_image, 
                                                :main_image,
                                                :thumb_image,
                                                :url,
                                                technologies_attributes: [:id, :name, :_destroy],
                                                )
    end
end

app/helpers/portfolio_items_helper.rb
module PortfolioItemsHelper

    def image_generator(height:, width:)
        "http://placehold.it/#{height}x#{width}"

    end

    def portfolio_item_img item, type
        # byebug
        # expects a PortfolioItemUploader object (carrierwave)
        # this is a bit wierd, as have to access thumb image up to model, down into value!!?!?!?! 
        # byebug
        if type == 'thumb'
            # byebug
            item.thumb_image.url || image_generator(height: '350', width: '200')
        else # 'main'
            item.main_image.url || image_generator(height: '600', width: '400')
        end
        # byebug
    end
    
end

app/views/portfolio_items/_form.html.erb
<%= form_with(model: portfolio_item, local: true) do |form| %>


<% if portfolio_item.errors.any? %>
<% portfolio_item.errors.full_messages.each do |error| %>
<%#= js add_gritter(error, title: 'Error!') %>
<%= alert_generator error %>
<% end %>



<!-- <div id="error_explanation">
  <h2>
    <%#= pluralize(portfolio_item.errors.count, "error") %> prohibited this portfolio_item from being saved:</h2>

  <ul>
    <%# portfolio_item.errors.full_messages.each do |message| %>
    <li>
      <%#= message %>
    </li>
    <%# end %>
  </ul>
</div> -->
<% end %>

<div class="row">

  <div class="col-md-6">

    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :subtitle %>
      <%= form.text_field :subtitle, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :url %>
      <%= form.text_field :url, class: 'form-control' %>
    </div>

    <h4>Imagery</h4>

    <div class="form-group">
      <%#= form.label :main_image %>
      <%#= form.file_field :main_image, class: 'form-control' %>
      <label class="btn btn-primary">
        Upload a main image file
        <%= form.file_field :main_image, style: 'display:none;' %>
      </label>
    </div>

    <div class="form-group">
      <%= form.label :thumb_image %>
      <%= form.file_field :thumb_image, class: 'form-control' %>
      <!-- <label class="btn btn-primary">
        Upload a thumbnail image file
        <%#= form.file_field :thumb_image, style: 'display:none;' %>
      </label> -->
    </div>

  </div>
  <div class="col-md-6">
    <div class="form-group">
      <%= form.label :body %>
      <%= form.text_area :body, class: 'form-control', rows: 13 %>
    </div>
  </div>

  <div class="col-md-6">
    <h3>Technologies and Practices used</h3>
    <div>
      <%= form.fields_for :technologies do |technology_form|%>
      <%= render 'technology_fields', f: technology_form %>
      <% end %>
      <!-- <%#= form.fields_for :technologies do |technology_form|%>
        <div class="form-group">
          <%#= technology_form.label :name %>
          <%#= technology_form.text_field :name, class: 'form-control' %>
        </div>
        <%# end %>
        </div> -->
      <div class="association">
        <%= link_to_add_association 'add technology', form, :technologies %>
      </div>
    </div>
    <div class="col-md-6">

      <!-- pre-upload -->
      <!-- <h4>Imagery</h4> -->
      <!-- <div class="form-group">
      <%#= form.label :main_image %>
      <%#= form.text_field :main_image, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%#= form.label :thumbnail_image %>
      <%#= form.text_field :thumb_image, class: 'form-control' %>
    </div> -->

      <div class="actions">
        <%= form.submit 'Save Portfolio Item', class: 'btn btn-primary btn-block' %>
      </div>
    </div>

  </div>

  <% end %>

app/views/portfolio_items/_portfolio_thing.html.erb
<div class="col-md-4">
    <div class="card mb-4 shadow-sm" data-id="<%= portfolio_thing.id %>">
        <%#=image_tag portfolio_thing.thumb_image.to_s, width: '100%' unless portfolio_thing.thumb_image.nil?%>
        <%# Want to return placeholder url if no real image uploaded %>
        <%# Following as now using PortfolioItemUploader 'mounted' against 2 image model fields %>
        <%#=image_tag portfolio_thing.thumb_image.to_s, width: '100%' %>
        <%#=image_tag portfolio_item_img(portfolio_thing, 'thumb'), width: '100%' %>

        <%#= link_to (image_tag portfolio_item_img(portfolio_thing, 'thumb'), width: '100%'), portfolio_item_show_path(portfolio_thing) %>
        <%= link_to (image_tag portfolio_item_img(portfolio_thing, 'thumb'), width: '100%'), portfolio_thing %>


        <div class="card-body">
            <p class="card-text">
                <h2>
                    <%#= link_to "{#{portfolio_thing.id}} [#{portfolio_thing.position || '--'}] ".html_safe + portfolio_thing.title, portfolio_item_show_path(portfolio_thing)%>
                    <%= link_to portfolio_thing.title, portfolio_thing%>
                </h2>
            </p>
            <h5>
                <%=portfolio_thing.subtitle%>
            </h5>
            <p>
                <%=portfolio_thing.body.truncate_words(15) %>
            </p>
            <h6>
                <% techs = [] %>
                <% portfolio_thing.technologies.each do | tech | %>
                <% techs.push(tech.name) %>
                <% end %>
                <%= techs.join(', ') %>
            </h6>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <!-- <button type="button" class="btn btn-sm btn-outline-secondary">View</button> -->
                    <!-- <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button> -->
                    <%= (link_to "Edit", edit_portfolio_item_path(portfolio_thing.id), class: "btn btn-sm btn-outline-primary") if logged_in?(:site_admin) %>
                    &nbsp;
                    <%= link_to "Delete", portfolio_item_path(portfolio_thing), class: "btn btn-sm btn-outline-secondary", method: :delete, data: { confirm: 'sure you wanna blow this away?'} if logged_in?(:site_admin) %>
                </div>
                <small class="text-muted">
                    <%= portfolio_thing.body.length %> words</small>
            </div>
        </div>
    </div>
</div>

<!-- 
<h2>
    <%#=link_to portfolio_thing.title, portfolio_item_show_path(portfolio_thing)%>
</h2>
<h4>
    <%#=portfolio_thing.subtitle%>
</h4>
<p>
    <%#=portfolio_thing.body%>
</p>
<p>
    <%#=image_tag portfolio_thing.thumb_image unless portfolio_thing.thumb_image.nil?%>
</p>
<p>
    <%#= link_to "Edit", edit_portfolio_item_path(portfolio_thing.id) if logged_in?(:site_admin) %>
</p>
<p>
    <%#= link_to "Delete (destroy)", portfolio_item_path(portfolio_thing), method: :delete, data: { confirm: 'sure you wanna blow this away?'} if logged_in?(:site_admin) %>
</p>
 -->

app/views/portfolio_items/_technology_fields.html.erb
<div class="form-group nested-fields">
    <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
    </div>
    <%= link_to_remove_association 'remove technology', f %>
</div>

app/views/portfolio_items/edit.html.erb
<div class="container portfolio-container">
    <h1>Editing Portfolio Item id:
        <%=@portfolio_item.id%>
    </h1>

    <%= render 'form', portfolio_item: @portfolio_item %>
    <!-- @portfolio_item links incorrectly to portfolio_items/:id, not the singular as we defined -->
    <!-- <%#= link_to 'Show', @portfolio_item %> | -->
    <%#= link_to 'cancel', portfolio_item_show_path(@portfolio_item) %> &nbsp;|&nbsp;
    <%= link_to 'cancel', @portfolio_item %> &nbsp;|&nbsp;
    <%= link_to 'view all portfolio items', portfolio_items_path %>
</div>

app/views/portfolio_items/index.html.erb
<div class="album py-5 bg-light">

    <div class="container portfolio-container">
        <%= link_to "Create a brand new Portfolio Item", new_portfolio_item_path if logged_in?(:site_admin) %>
        <div class="row <%=" sortable" if logged_in?(:site_admin) %>">

            <!-- <h1>Portfolio Items</h1> -->

            <!-- <p id="notice"><%#= notice %></p> -->

            <%# partials with manual / override collections %>
            <%# binding.pry %>

            <%= render partial: 'portfolio_thing', collection: @portfolio_items %>

        </div>
    </div>
</div>

app/views/portfolio_items/javascript_portfolio_items.html.erb
<h1>Javascript Portfolio Items</h1>

<%= link_to "Create new Portfolio Item", new_portfolio_item_path %>
<%# binding.pry %>
<% @javascript_portfolio_items.each do |portfolio_item| %>
<h2>
    <%#=link_to portfolio_item.title, portfolio_item_show_path(portfolio_item)%>
    <%=link_to portfolio_item.title, portfolio_item%>
</h2>
<h4>
    <%=portfolio_item.subtitle%>
</h4>
<p>
    <%=portfolio_item.body%>
</p>
<p>
    <%=image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil?%>
</p>
<p>
    <%= link_to "Edit", edit_portfolio_item_path(portfolio_item.id) %>
</p>
<p>
    <%= link_to "Delete (destroy)", portfolio_item_path(portfolio_item), method: :delete, data: { confirm: 'sure you wanna blow this away?'} %>
</p>
<% end %>

app/views/portfolio_items/new.html.erb
<div class="container portfolio-container">

    <h1>Create a new Portfolio Item</h1>

    <%= render 'form', portfolio_item: @portfolio_item %>

    <%= link_to 'Cancel', portfolio_items_path %>

</div>

app/views/portfolio_items/show.html.erb
<div class="container portfolio-container">

    <div class="row">
        <!-- <p id="notice"><%#= notice %></p> -->

        <div class="col-md-7">
            <%#=image_tag @portfolio_item.main_image.to_s, width: '100%' unless @portfolio_item.main_image.nil?%>
            <%=image_tag portfolio_item_img(@portfolio_item, 'main'), width: '100%' unless @portfolio_item.main_image.nil?%>

        </div>
        <div class="col-md-5">
            <h1>
                <%=@portfolio_item.title%>
            </h1>
            <h3>
                <em>
                    <%=@portfolio_item.subtitle%>
                </em>
            </h3>
            <h5>
                <em>
                    <a href="//<%=@portfolio_item.url %>" target="_blank">
                        <%=@portfolio_item.url%>
                    </a>
                </em>
            </h5>
            <p>
                <%=@portfolio_item.body%>
            </p>

            <h4>Technologies and practices</h4>

            <% @portfolio_item.technologies.each do |t| %>
            <p>
                <%= t.name %>
            </p>
            <% end %>
            <% if logged_in?(:site_admin) %>
            <div class="col-md-12">
                <%= link_to 'Edit', edit_portfolio_item_path(@portfolio_item), class: 'btn btn-primary' %>
                <%= link_to 'Destroy', portfolio_item_path(@portfolio_item), method: :delete, data: {confirm: "Blow away blog # #{@portfolio_item.id}?"}, class: 'btn btn-warning'  %>
                <% end %>
            </div>
        </div>

    </div>
    <div class="col-md-12">
        <%= link_to 'View all Portfolio Items', portfolio_items_path %>
    </div>

</div>

<!-- 
<hr />

<%#= params[:id].inspect %>
<br />
<%#= params[:action].inspect %>
<br />
<%#= params[:controller].inspect %>
<br />
<%#= PortfolioItem.find(params[:id]).title %>

<hr /> -->


<%#=  session.inspect %>